const visitTile = (tileX, tileY, facingPoint, metadata = {}) => ({
    tileX,
    tileY,
    facingPoint,
    ...metadata,
});

const workSlot = (tileX, tileY, facingPoint, metadata = {}) => visitTile(tileX, tileY, facingPoint, {
    role: 'work',
    stance: 'front',
    priority: 100,
    capacityWeight: 1,
    ...metadata,
});

const queueSlot = (tileX, tileY, facingPoint, metadata = {}) => visitTile(tileX, tileY, facingPoint, {
    role: 'queue',
    stance: 'waiting',
    priority: 60,
    capacityWeight: 0.65,
    overflow: true,
    ...metadata,
});

const scenicSlot = (tileX, tileY, facingPoint, metadata = {}) => visitTile(tileX, tileY, facingPoint, {
    role: 'ambient',
    stance: 'observe',
    priority: 30,
    capacityWeight: 0.35,
    scenic: true,
    ...metadata,
});

export const normalizeBuildingType = (type) => {
    const value = String(type || '').trim();
    if (!value) return null;
    return value === 'lighthouse' ? 'watchtower' : value;
};

export const VISIT_OVERFLOW_TILES = Object.freeze({
    archive: [
        { tileX: 7, tileY: 19, overflow: true, reason: 'archive-walk' },
        { tileX: 8, tileY: 20, overflow: true, reason: 'reading-alcove' },
        { tileX: 9, tileY: 19, overflow: true, reason: 'archive-walk' },
        { tileX: 9, tileY: 20, overflow: true, reason: 'reading-alcove' },
        { tileX: 10, tileY: 19, overflow: true, reason: 'archive-walk' },
    ],
    command: [
        { tileX: 14, tileY: 22, overflow: true, reason: 'plaza' },
        { tileX: 19, tileY: 22, overflow: true, reason: 'plaza' },
        { tileX: 13, tileY: 22, overflow: true, reason: 'plaza' },
    ],
    taskboard: [
        { tileX: 22, tileY: 36, overflow: true, reason: 'review' },
        { tileX: 27, tileY: 36, overflow: true, reason: 'review' },
    ],
    mine: [
        { tileX: 9, tileY: 34, overflow: true, reason: 'mine-yard' },
        { tileX: 10, tileY: 36, overflow: true, reason: 'mine-yard' },
        { tileX: 13, tileY: 37, overflow: true, reason: 'cart-path' },
        { tileX: 16, tileY: 34, overflow: true, reason: 'ore-sort' },
        { tileX: 16, tileY: 36, overflow: true, reason: 'ore-sort' },
    ],
    watchtower: [
        { tileX: 27, tileY: 16, overflow: true, reason: 'lookout' },
        { tileX: 26, tileY: 15, overflow: true, reason: 'lookout' },
    ],
});

export const BUILDING_DEFS = [
    {
        type: 'command',
        x: 13,
        y: 16,
        width: 5,
        height: 4,
        label: 'COMMAND CENTER',
        shortLabel: 'COMMAND',
        icon: 'C',
        description: 'Team status',
        district: 'civic',
        capacity: { work: 5, ambient: 3, overflow: 3 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 15, tileY: 21 },
        visitTiles: [
            workSlot(15, 21, { x: 15.5, y: 18.0 }, { queueGroup: 'command-briefing', stance: 'briefing' }),
            workSlot(14, 21, { x: 15.5, y: 18.0 }, { queueGroup: 'command-briefing', stance: 'briefing' }),
            workSlot(18, 21, { x: 15.5, y: 18.0 }, { queueGroup: 'command-briefing', stance: 'briefing' }),
            queueSlot(15, 22, { x: 15.5, y: 18.0 }, { queueGroup: 'command-plaza', reason: 'plaza' }),
            queueSlot(18, 22, { x: 15.5, y: 18.0 }, { queueGroup: 'command-plaza', reason: 'plaza' }),
            scenicSlot(12, 18, { x: 15.5, y: 18.0 }, { queueGroup: 'command-wing', stance: 'watch' }),
            scenicSlot(12, 19, { x: 15.5, y: 18.0 }, { queueGroup: 'command-wing', stance: 'watch' }),
            scenicSlot(18, 18, { x: 15.5, y: 18.0 }, { queueGroup: 'command-wing', stance: 'watch' }),
            scenicSlot(18, 19, { x: 15.5, y: 18.0 }, { queueGroup: 'command-wing', stance: 'watch' }),
        ],
        walkExclusion: [{ dx: 0, dy: 4, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 10.5, y0: 12.5, x1: 20.5, y1: 22.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'taskboard',
        x: 23,
        y: 33,
        width: 4,
        height: 3,
        label: 'TASK BOARD',
        shortLabel: 'TASKS',
        icon: 'B',
        description: 'Task status',
        district: 'civic',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 25, tileY: 37 },
        visitTiles: [
            workSlot(25, 37, { x: 25.0, y: 35.5 }, { queueGroup: 'task-review', stance: 'review' }),
            workSlot(23, 37, { x: 25.0, y: 35.5 }, { queueGroup: 'task-review', stance: 'review' }),
            workSlot(27, 37, { x: 25.0, y: 35.5 }, { queueGroup: 'task-review', stance: 'review' }),
            queueSlot(24, 38, { x: 25.0, y: 35.5 }, { queueGroup: 'task-review', reason: 'review' }),
            queueSlot(26, 38, { x: 25.0, y: 35.5 }, { queueGroup: 'task-review', reason: 'review' }),
            scenicSlot(22, 34, { x: 25.0, y: 35.5 }, { queueGroup: 'task-observe', stance: 'read' }),
            scenicSlot(22, 35, { x: 25.0, y: 35.5 }, { queueGroup: 'task-observe', stance: 'read' }),
            scenicSlot(27, 34, { x: 25.0, y: 35.5 }, { queueGroup: 'task-observe', stance: 'read' }),
            scenicSlot(27, 35, { x: 25.0, y: 35.5 }, { queueGroup: 'task-observe', stance: 'read' }),
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 4, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 21.5, y0: 30.5, x1: 28.5, y1: 37.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'forge',
        x: 26,
        y: 26,
        width: 4,
        height: 3,
        label: 'CODE FORGE',
        shortLabel: 'FORGE',
        icon: 'F',
        description: 'Code work',
        district: 'workshop',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 25, tileY: 30 },
        visitTiles: [
            workSlot(25, 30, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-anvil', stance: 'hammer' }),
            workSlot(28, 30, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-anvil', stance: 'hammer' }),
            queueSlot(25, 31, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-yard', reason: 'forge-yard' }),
            queueSlot(27, 31, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-yard', reason: 'forge-yard' }),
            queueSlot(30, 31, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-yard', reason: 'forge-yard' }),
            scenicSlot(25, 28, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-watch', stance: 'warm-hands' }),
            scenicSlot(30, 29, { x: 27.5, y: 27.5 }, { queueGroup: 'forge-watch', stance: 'warm-hands' }),
        ],
        walkExclusion: [{ dx: -1, dy: 3, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 23.5, y0: 24.5, x1: 31.5, y1: 30.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'mine',
        x: 11,
        y: 31,
        width: 4,
        height: 3,
        label: 'TOKEN MINE',
        shortLabel: 'MINE',
        icon: 'T',
        description: 'Token usage',
        district: 'resource',
        capacity: { work: 3, ambient: 2, overflow: 2 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 13, tileY: 35 },
        visitTiles: [
            workSlot(13, 35, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-mouth', stance: 'inspect' }),
            workSlot(11, 35, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-mouth', stance: 'inspect' }),
            workSlot(15, 35, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-mouth', stance: 'inspect' }),
            queueSlot(12, 36, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-cart', reason: 'cart-path' }),
            queueSlot(14, 36, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-cart', reason: 'cart-path' }),
            scenicSlot(10, 33, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-yard', stance: 'sort', reason: 'ore-sort' }),
            scenicSlot(15, 33, { x: 13.0, y: 32.5 }, { queueGroup: 'mine-yard', stance: 'sort', reason: 'ore-sort' }),
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 4, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 9.5, y0: 29.5, x1: 16.5, y1: 35.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'archive',
        x: 3,
        y: 15,
        width: 5,
        height: 3,
        label: 'GRAND LORE ARCHIVE',
        shortLabel: 'ARCHIVE',
        icon: 'A',
        description: 'Reading and search',
        district: 'knowledge',
        capacity: { work: 4, ambient: 2, overflow: 6 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 8, tileY: 17 },
        visitTiles: [
            workSlot(8, 17, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-desk', stance: 'read' }),
            workSlot(8, 16, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-desk', stance: 'read' }),
            workSlot(8, 18, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-desk', stance: 'read' }),
            workSlot(9, 17, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-desk', stance: 'search' }),
            queueSlot(9, 18, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-aisle', stance: 'browse', reason: 'archive-walk' }),
            scenicSlot(8, 19, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-alcove', stance: 'browse', reason: 'reading-alcove' }),
            scenicSlot(9, 16, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-alcove', stance: 'browse', reason: 'reading-alcove' }),
            scenicSlot(10, 17, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-alcove', stance: 'browse', reason: 'reading-alcove' }),
            scenicSlot(10, 18, { x: 5.5, y: 16.5 }, { queueGroup: 'archive-aisle', stance: 'browse', reason: 'archive-walk' }),
        ],
        walkExclusion: [{ dx: 0, dy: 3, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 1.0, y0: 11.0, x1: 10.2, y1: 20.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'observatory',
        x: 21,
        y: 14,
        width: 4,
        height: 4,
        label: 'RESEARCH OBSERVATORY',
        shortLabel: 'OBSERVATORY',
        icon: '*',
        description: 'External research and skywatch',
        district: 'knowledge',
        capacity: { work: 3, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 23, tileY: 18 },
        visitTiles: [
            workSlot(23, 18, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-lens', stance: 'observe' }),
            workSlot(22, 19, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-lens', stance: 'observe' }),
            workSlot(24, 19, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-lens', stance: 'observe' }),
            scenicSlot(20, 16, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-terrace', stance: 'skywatch' }),
            scenicSlot(20, 17, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-terrace', stance: 'skywatch' }),
            queueSlot(21, 18, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-lens', reason: 'skywatch' }),
            queueSlot(25, 18, { x: 22.5, y: 16.0 }, { queueGroup: 'observatory-lens', reason: 'skywatch' }),
        ],
        walkExclusion: [{ dx: 4, dy: 1, width: 1, height: 3 }],
        scenery: {
            excludePadding: { x: 2, y: 1 },
            sightline: { x0: 19.2, y0: 6.8, x1: 28.8, y1: 19.4 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'portal',
        x: 2,
        y: 29,
        width: 4,
        height: 4,
        label: 'PORTAL GATE',
        shortLabel: 'PORTAL',
        icon: 'O',
        description: 'Browser and remote tools',
        district: 'arcane',
        capacity: { work: 4, ambient: 2, overflow: 2 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 6, tileY: 34 },
        visitTiles: [
            workSlot(6, 34, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-threshold', stance: 'summon' }),
            workSlot(2, 34, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-threshold', stance: 'summon' }),
            workSlot(4, 34, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-threshold', stance: 'summon' }),
            queueSlot(3, 35, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-court', reason: 'portal-court' }),
            queueSlot(5, 35, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-court', reason: 'portal-court' }),
            scenicSlot(6, 30, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-runes', stance: 'ward' }),
            scenicSlot(6, 32, { x: 3.5, y: 31.0 }, { queueGroup: 'portal-runes', stance: 'ward' }),
        ],
        walkExclusion: [{ dx: 0, dy: 4, width: 5, height: 1 }],
        scenery: {
            excludePadding: { x: 1, y: 1 },
            sightline: { x0: 0.5, y0: 27.0, x1: 7.5, y1: 34.5 },
            tallPropClearance: 1,
        },
    },
    {
        type: 'watchtower',
        x: 27,
        y: 8,
        width: 3,
        height: 5,
        label: 'PHAROS LIGHTHOUSE',
        shortLabel: 'LIGHTHOUSE',
        icon: 'L',
        description: 'Sea watch and beacon',
        district: 'harbor',
        capacity: { work: 2, ambient: 1, overflow: 1 },
        visualTier: 'hero',
        labelPriority: 'landmark',
        entrance: { tileX: 28, tileY: 14 },
        visitTiles: [
            workSlot(28, 14, { x: 28.0, y: 10.5 }, { queueGroup: 'watchtower-beacon', stance: 'signal' }),
            queueSlot(27, 14, { x: 28.0, y: 10.5 }, { queueGroup: 'watchtower-lookout', reason: 'lookout' }),
            scenicSlot(27, 15, { x: 28.0, y: 10.5 }, { queueGroup: 'watchtower-lookout', stance: 'scan', reason: 'lookout' }),
            scenicSlot(28, 16, { x: 28.0, y: 10.5 }, { queueGroup: 'watchtower-lookout', stance: 'scan', reason: 'lookout' }),
        ],
        walkExclusion: [{ dx: 0, dy: 5, width: 3, height: 1 }],
        scenery: {
            excludePadding: { x: 2, y: 2 },
            sightline: { x0: 24.5, y0: 4.5, x1: 32.0, y1: 15.5 },
            tallPropClearance: 2,
        },
    },
    {
        type: 'harbor',
        x: 30,
        y: 17,
        width: 5,
        height: 4,
        label: 'HARBOR MASTER',
        shortLabel: 'HARBOR',
        icon: 'H',
        description: 'Commit ships and push departures',
        district: 'harbor',
        capacity: { work: 4, ambient: 3, overflow: 3 },
        visualTier: 'major',
        labelPriority: 'landmark',
        entrance: { tileX: 28, tileY: 19 },
        visitTiles: [
            workSlot(28, 19, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-ledger', stance: 'dispatch' }),
            workSlot(28, 18, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-ledger', stance: 'dispatch' }),
            workSlot(28, 20, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-ledger', stance: 'dispatch' }),
            queueSlot(27, 19, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-quay', reason: 'quay' }),
            scenicSlot(27, 17, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-quay', stance: 'watch', reason: 'quay' }),
            queueSlot(27, 21, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-pier', reason: 'pier' }),
            scenicSlot(26, 21, { x: 34.0, y: 19.0 }, { queueGroup: 'harbor-pier', stance: 'watch', reason: 'pier' }),
        ],
        walkExclusion: [{ dx: -1, dy: 0, width: 1, height: 4 }],
        scenery: {
            excludePadding: { x: 2, y: 1 },
            sightline: { x0: 28.5, y0: 14.5, x1: 36.5, y1: 21.5 },
            tallPropClearance: 2,
        },
    },
];
