export const TILE_WIDTH = 64;
export const TILE_HEIGHT = 32;
export const MAP_SIZE = 40;
export const REFRESH_INTERVAL = 2000;
export const SESSION_DETAIL_PANEL_REFRESH_INTERVAL = 2000;
export const SESSION_DETAIL_REFRESH_INTERVAL = 3000;
export const WS_RECONNECT_INTERVAL = 3000;
